const NEWSLETTERS_BUCKET_NAME = 'aws-frontend-newsletters-source';
const SHEET_VERSION = '0.6a';
const SHEET_NAME = 'Emails';
const SHEET_RANGE = 'A:AG';
const PREVIEW_INDEX = 19;
const FREQUENCY_INDEX = 4;
const GROUP_INDEX = 2;
const THEME_INDEX = 0;

export {
	FREQUENCY_INDEX,
	GROUP_INDEX,
	NEWSLETTERS_BUCKET_NAME,
	PREVIEW_INDEX,
	SHEET_NAME,
	SHEET_RANGE,
	SHEET_VERSION,
	THEME_INDEX,
};
