name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: guardian/actions-assume-aws-role@v1
        with:
          awsRoleToAssume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: guardian/actions-setup-node@main

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn upload-artifact
