name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./v0
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: guardian/actions-setup-node@main

      - name: Install
        run: yarn

      - name: Test
        run: yarn test
