name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: guardian/actions-setup-node@main

      - name: Go to v0 directory
        run: cd v0

      - name: Install
        run: yarn

      - name: Test
        run: yarn test
