name: Typescript
on:
  push:
jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: guardian/actions-setup-node@main

      - name: Install
        run: yarn

      - name: Typescript
        run: yarn tsc
